### PR TITLE
Fix js error when no proposal field on determination form.

### LINKED ISSUE #4144: Determination page shows `Uncaught TypeError` in console
**Describe the bug**

On the determination page, when looking in the JavaScript console (web developer tools) an error occurs when looking for a page element.

**To Reproduce**

1. Using the sandbox db
2. Visit determination page for submission, e.g. `apply/submissions/2/determination/2/edit/`
3. Open developer tools, view JS console
4. See the error:
```
Uncaught TypeError: proposal_form_field is null
    <anonymous> https://hypha.test/static/js/determination-template.js:53
    EventListener.handleEvent* https://hypha.test/static/js/determination-template.js:51
    <anonymous> https://hypha.test/static/js/determination-template.js:57
```

**Expected behavior**

No such error.

**Priority**

- Low priority (annoying, would be nice to not see)

**Affected roles**

- Developers

**Screenshots**

**Desktop (please complete the following information):**

 - OS: Trisquel 11.0
 - Browser: Abrowser (Firefox-ish) 128.0.3

**Additional context**

See #4142 (context in which issue was found) and #3425 (probable origin of issue).

I can't find an element with id `id_proposal_form` in current main at a5d3a4f5e8257af713683cfcbe3e37719d4fa152 or in the commit in #3425 that created the related JavaScript.

### PR DESCRIPTION
**Pull request by frjo**
Fixes #4144

### CODE REVIEW

File: hypha/static_src/javascript/determination-template.js [hunk 1]
```diff
@@ -69,7 +69,7 @@
     });
     window.addEventListener("load", function (event) {
         const proposal_form_field = document.querySelector("#id_proposal_form");
```
Comment (bickelj) [inline hypha/static_src/javascript/determination-template.js:71]: It's probably not important, but how or where does `id_proposal_form` come from? I could not find it anywhere.

Comment (frjo) [reply hypha/static_src/javascript/determination-template.js:71]: See https://github.com/HyphaApp/hypha/blob/a5d3a4f5e8257af713683cfcbe3e37719d4fa152/hypha/apply/determinations/forms.py#L368-L393
